# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('squeezemail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subscriber',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='lap',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='from_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='from_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('paused', 'Paused'), ('active', 'Active')], max_length=15),
        ),
    ]
