# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squeezemail', '0003_auto_20160909_2115'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subscriber',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='decision',
            name='description',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='description',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='delay',
            name='delay',
            field=models.CharField(default='1 days', max_length=255),
        ),
    ]
